# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FBYf9yUX/0PwFT/lKwYg7cyFdZFRjHjbX6Sv9kPVQHuzJlZzMgUzwvv2/D3lUBpIQqL9oNxHoHlrVN8NCAk/7v/inUE6BUZk+CYfvwSwxaJukzrNNPzweksLm3HmJ8xrLnhj/8hSqe8U4Xo1ly8810wSaTGUPEZ0+C8G86MygWo9rYZOPt6N+m3bORIJncNITLa0T9nit9pnAGqEBlxh9G4fc7Y+dZUfZJCBZgNg2wtMqffR+nX0EnnO4ECFxTmn7Z0Ay/1meowsd5h4/+NjJsIdDJdf/NMIGZpPxgGwR5l4rQcqc+sGkl9//k1oYH7h75odK6RAn3gZVmc/UtaoLVxvGN4ykhfv0Kg5ZBs3szetaar73KGYCiuIs/nbYHqBVGR4Q1M6QNvqVtRZwe+u4F/VXtg6yB8w5Ej5tGZZ+Y4l9Mf0X2d1srGr+l7gjlQef+dun42hDVoyyXI7AMgmzMOWVmucfgiUufuz2enNrujvehqGuwi1xObt4mJvRXunyNUUQGKbNCwKe3FlPPpOYNQTo8T2BTR0+46PWAceiCZVbrEqfiPtWiCuAiBYk0hbYSWV4oE+so+AKBUrqyd30w+ihwI7nQDG3AnJ9MOiyL15QlXGcoBVeckACHb1ZQYrpjgTFT36dCkeL4FdETHcHWP3qbBdecfa2XiVxE/6W4Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
