travis:
  secure:
    BINSTAR_TOKEN: nFtD2jej2CrX/ydDy/UKubvC+AaHIhV04D8Uf3bEfcZSbBiXwh83pRL/v5EOApV4299wQwNrqZ7H31hhBJRvYRA1RPIsHEgO+AIAzXsuf/KoxfCrpOTaObIZp9/Dqxy5TEIyzLX3uqbbWgbC3rLlsxCLObiI1/bL+4jZovS69Z2goCX/HVgnw3xWXBD9e6dUzDrSiqiFf8vLg0i5ccn4imdym1/wvEYizUmDmwPXvINO5g5bIv7gh1glsKiQaKwXEr7Vexv8Jy6cdiAOCkP+25lwNZxDVpPBtVSEju3i28HgD/XTOvB4QSMmOftdw+piydOZjJGyKwin8BTMSUfSjxzFUTa/ro4B18mxyVAdYICIPeXYBz2maHcydeS/kH3raZ4HUCZ6X+DZs9Wp7LCFWV/4UgR08YgxmLOy8/HtW2w/RRiTaqrdjT+oMgjQeV8DFjThOU/L7YVVUVMDijz73tZ7KEktatdBloaR+6b5/aK81WsrdGPlFJ6L8ZlGONM4/59qgmlO8kZ+5iuLYlVUGfl555q2ZIK/67DL/pBv4BZnI2Tb3U2ACUkmnwRW9Ep+P6ac70LrMduB2D4aA8u09+5suFwioF59pFQasT4rLKlukqqdpuyDTP3IHXYdggk1lVRQw+nfxJIqU/nBHIxspUFWCnGpKOFfdpamibQbh1I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
