travis:
  secure:
    BINSTAR_TOKEN: FBYf9yUX/0PwFT/lKwYg7cyFdZFRjHjbX6Sv9kPVQHuzJlZzMgUzwvv2/D3lUBpIQqL9oNxHoHlrVN8NCAk/7v/inUE6BUZk+CYfvwSwxaJukzrNNPzweksLm3HmJ8xrLnhj/8hSqe8U4Xo1ly8810wSaTGUPEZ0+C8G86MygWo9rYZOPt6N+m3bORIJncNITLa0T9nit9pnAGqEBlxh9G4fc7Y+dZUfZJCBZgNg2wtMqffR+nX0EnnO4ECFxTmn7Z0Ay/1meowsd5h4/+NjJsIdDJdf/NMIGZpPxgGwR5l4rQcqc+sGkl9//k1oYH7h75odK6RAn3gZVmc/UtaoLVxvGN4ykhfv0Kg5ZBs3szetaar73KGYCiuIs/nbYHqBVGR4Q1M6QNvqVtRZwe+u4F/VXtg6yB8w5Ej5tGZZ+Y4l9Mf0X2d1srGr+l7gjlQef+dun42hDVoyyXI7AMgmzMOWVmucfgiUufuz2enNrujvehqGuwi1xObt4mJvRXunyNUUQGKbNCwKe3FlPPpOYNQTo8T2BTR0+46PWAceiCZVbrEqfiPtWiCuAiBYk0hbYSWV4oE+so+AKBUrqyd30w+ihwI7nQDG3AnJ9MOiyL15QlXGcoBVeckACHb1ZQYrpjgTFT36dCkeL4FdETHcHWP3qbBdecfa2XiVxE/6W4Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
